version: "3.8"

services:
  api:
    build: api
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: air ./main.go -b 0.0.0.0 -c .air.toml
     
  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data